# Generated by Django 5.1.3 on 2024-12-07 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_mymodel_remove_book_publication_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_date',
            field=models.DateField(default='2024-01-01'),
        ),
    ]
